version: "3"
services:
  postgres:
    image: timescale/timescaledb:2.13.1-pg16
    container_name: kaivest-postgres
    env_file:
      - ".env"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
